import { createTypes } from 'reduxsauce';

export default createTypes(`
  UPDATE_SEARCH_ROOMS
  UPDATE_ACTIVE_FLOOR
  UPDATE_ACTIVE_SECTION
  SET_ACTIVE_ROOMS
  SET_ACTIVE_FLOOR_ROOMS

  TOGGLE_NON_GUEST_ROOMS

  RESET_ROOM_FILTERS

  SET_ROOM_TYPE

  UPDATE_SEARCH_TASK

  SET_GROUP_ASSIGNEE
  SET_ACTIVE_GROUP_ASSIGNEE


  SET_ACTIVE_ALL_ROOMS
  UPDATE_ALL_SEARCH_ROOMS
  RESET_ALL_ROOM_FILTERS

  SET_ROOM_LOCATION
`);
