import { createTypes } from 'reduxsauce';

export default createTypes(`
    AVAILABLE_HOTEL_TASK_RESET

    ACTIVE_AVAIL_HOTEL

    AVAILABLE_HOTEL_TASK_FETCH
    AVAILABLE_HOTEL_TASK_SUCCESS
    AVAILABLE_HOTEL_FAILURE

    AVAILABLE_HOTEL_FUTURE_TASK_FETCH
    AVAILABLE_HOTEL_FUTURE_TASK_SUCCESS
    AVAILABLE_HOTEL_FUTURE_TASK_FAILURE

    AVAILABLE_HOTEL_ROOM_FETCH
    AVAILABLE_HOTEL_ROOM_SUCCESS
    AVAILABLE_HOTEL_ROOM_FAILURE
`);
