import { createTypes } from 'reduxsauce';

export default createTypes(`
  UPDATE_SEARCH_ROOMS
  UPDATE_FLOOR_OPERATION
  UPDATE_FLOOR_SECTION_OPERATION

  UPDATE_ROOM_FILTER_OPERATION

  UPDATE_ROOM_TYPE_OPERATION

  UPDATE_ACTIVE_FLOOR
  UPDATE_ACTIVE_SECTION
  SET_ACTIVE_ROOMS
  SET_ACTIVE_FLOOR_ROOMS

  TOGGLE_NON_GUEST_ROOMS

  RESET_ROOM_FILTERS
  RESET_FLOOR_FILTERS

  SET_ROOM_TYPE
`);
