import { createTypes } from 'reduxsauce';

export default createTypes(`
  RESET_ROOMS

  ROOM_ACTIVATE
  ROOM_DEACTIVATE

  ROOMS_FETCH
  ROOMS_SUCCESS
  ROOMS_FAILURE
  ROOMS_UPDATES
  ROOMS_UPDATE_READ
  ROOMS_UNBLOCKS
  ROOMS_UNBLOCKS_READ
  SINGLE_ROOM_SUCCESS

  ROOM_UPDATE_OPTIMISTIC
  ROOM_UPDATE_SUCCESS

  FLOORS_FETCH
  FLOORS_SUCCESS
  FLOORS_FAILURE

  ROOM_STATUSES_FETCH
  ROOM_STATUSES_SUCCESS
  ROOM_STATUSES_FAILURE

  ROOM_HOUSEKEEPINGS_FETCH
  ROOM_HOUSEKEEPINGS_SUCCESS
  ROOM_HOUSEKEEPINGS_FAILURE
  SINGLE_ROOM_HOUSEKEEPINGS_SUCCESS

  ROOM_CATEGORY_FETCH
  ROOM_CATEGORY_SUCCESS
  ROOM_CATEGORY_FAILURE

  PLANNINGS_FETCH
  PLANNINGS_SUCCESS
  PLANNINGS_FAILURE

  FUTURE_PLANNINGS_FETCH
  FUTURE_PLANNINGS_SUCCESS
  FUTURE_PLANNINGS_FAILURE

  PLANNINGS_UPDATES
  PLANNINGS_UPDATE_READ

  PLANNING_UPDATE_OPTIMISTIC

  PLANNINGS_NIGHT_FETCH
  PLANNINGS_NIGHT_SUCCESS
  PLANNINGS_NIGHT_FAILURE

  PLANNINGS_RUNNER_FETCH
  PLANNINGS_RUNNER_SUCCESS
  PLANNINGS_RUNNER_FAILURE

  CALENDAR_FETCH
  CALENDAR_SUCCESS
  CALENDAR_FAILURE

  ROOM_NOTES_FETCH
  ROOM_NOTES_SUCCESS
  ROOM_NOTES_FAILURE

  CATALOGS_FETCH
  CATALOGS_SUCCESS
  CATALOGS_FAILURE

  LOST_FETCH
  LOST_FETCH_SUCCESS
  LOST_FETCH_FAILURE

  FOUND_FETCH
  FOUND_FETCH_SUCCESS
  FOUND_FETCH_FAILURE

  TASKS_FETCH
  TASKS_SUCCESS
  TASKS_FAILURE

  FUTURE_TASKS_FETCH
  FUTURE_TASKS_SUCCESS
  FUTURE_TASKS_FAILURE

  TASK_UPDATE_OPTIMISTIC
  TASK_UPDATE_SUCCESS

  HISTORY_FETCH
  HISTORY_SUCCESS
  HISTORY_FAILURE

  BOOKMARK_ADD
  BOOKMARK_REMOVE
  BOOKMARKS_CLEAR

  GUEST_BOOK_FETCH
  GUEST_BOOK_FETCH_SUCCESS
  GUEST_BOOK_FETCH_FAILURE

  PLANNINGS_HOSTS_IN_FETCH
  PLANNINGS_HOSTS_IN_FETCH_SUCCESS
  PLANNINGS_HOSTS_IN_FETCH_FAILURE
  PLANNINGS_HOSTS_OUT_FETCH
  PLANNINGS_HOSTS_OUT_FETCH_SUCCESS
  PLANNINGS_HOSTS_OUT_FETCH_FAILURE

  EXTRA_OPTION_UPDATE_OPTIMISTIC

  UPDATE_ROOMS_INCREMENT

  ROOM_MESSAGES_FETCH
  SOCKET_ROOM_MESSAGES_FETCH
  ROOM_MESSAGES_SUCCESS

  ROOM_INSPECTION_CLEAN_FETCH
  ROOM_INSPECTION_CLEAN_SUCCESS

  AUDIT_FETCH
  AUDIT_SUCCESS
  AUDIT_FAILURE
  SET_SECONDARY_CLEANING
  
  IS_SOCKET_FIRE_ON_UPDATE_INSPECTION

  SOCKET_FIRE_DATE_TIME

  SOCKET_FIRE_LOADER

  SOCKET_LIST
  
  SET_TASK_SOCKET_DATA

  CAME_TO_BREAKFAST
  RESERVATION_CAME_TO_BREAKFAST
  RESERVATION_CAME_TO_BREAKFAST_SUCCESS
  RESERVATION_CAME_TO_BREAKFAST_FAILURE

  BREAKFAST_FETCH
  GET_BREAKFAST_SUCCESS
  GET_BREAKFAST_FAILURE

  ALL_HOTEL_PLANNINGS_FETCH
  ALL_HOTEL_PLANNINGS_SUCCESS
  ALL_HOTEL_PLANNINGS_FAILURE
`);
