import OutboundTypes from "rc-mobile-base/lib/constants/outbound"

export const reduxOfflineActions = [
    OutboundTypes.OUTBOUND_RESET,

    OutboundTypes.OUTBOUND_ROOM_CLEAN_START,
    OutboundTypes.OUTBOUND_ROOM_CLEAN_RESTART,
    OutboundTypes.OUTBOUND_ROOM_CLEAN_PAUSE,
    OutboundTypes.OUTBOUND_ROOM_CLEAN_UNPAUSE,
    OutboundTypes.OUTBOUND_ROOM_CLEAN_FINISH,

    OutboundTypes.OUTBOUND_ROOM_DELAY,
    OutboundTypes.OUTBOUND_ROOM_DND,
    OutboundTypes.OUTBOUND_ROOM_REFUSE,
    OutboundTypes.OUTBOUND_ROOM_VOUCHER,
    OutboundTypes.OUTBOUND_ROOM_INSPECT,
    OutboundTypes.OUTBOUND_ROOM_NO_CHECK,
    OutboundTypes.OUTBOUND_ROOM_CONFIRM_DND,
    OutboundTypes.OUTBOUND_ROOM_CANCEL,
    OutboundTypes.OUTBOUND_ROOM_RESET,
    OutboundTypes.OUTBOUND_ROOM_RESET_FAILURE,

    OutboundTypes.OUTBOUND_ROOM_MODEL_UPDATE,
    OutboundTypes.OUTBOUND_ROOM_ATTENDANT_INSPECT,

    OutboundTypes.OUTBOUND_ROOM_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_ROOM_HOUSEKEEPING_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_ROOM_CLEAN_FAILURE,
    OutboundTypes.OUTBOUND_ROOM_UPDATE_FAILURE,

    OutboundTypes.OUTBOUND_LOG_OTHER,
    OutboundTypes.OUTBOUND_LOG_CLEAN,
    OutboundTypes.OUTBOUND_LOG_COMPLETED,
    OutboundTypes.OUTBOUND_LOG_FAILURE,

    OutboundTypes.OUTBOUND_SUBMIT_FOUND_ITEM,
    OutboundTypes.OUTBOUND_SUBMIT_FOUND_ITEM_SUCCESS,
    OutboundTypes.OUTBOUND_SUBMIT_FOUND_ITEM_FAILURE,

    OutboundTypes.OUTBOUND_TASK_CREATE,
    OutboundTypes.OUTBOUND_TASK_CREATE_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_CREATE_FAILURE,
    OutboundTypes.OUTBOUND_TASK_PHOTO_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_PHOTO_FAILURE,

    OutboundTypes.OUTBOUND_TASKS_CREATE,
    OutboundTypes.OUTBOUND_TASKS_CREATE_SUCCESS,
    OutboundTypes.OUTBOUND_TASKS_CREATE_FAILURE,

    OutboundTypes.OUTBOUND_TASK_UPDATE,
    OutboundTypes.OUTBOUND_TASK_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_UPDATE_FAILURE,

    OutboundTypes.OUTBOUND_TASK_UPDATE_BATCH,
    OutboundTypes.OUTBOUND_TASK_UPDATE_BATCH_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_UPDATE_BATCH_FAILURE,

    OutboundTypes.OUTBOUND_CREATE_TASK_MESSAGE,
    OutboundTypes.OUTBOUND_CREATE_TASK_MESSAGE_SUCCESS,
    OutboundTypes.OUTBOUND_CREATE_TASK_MESSAGE_FAILURE,

    OutboundTypes.OUTBOUND_TASK_REASSIGN,
    OutboundTypes.OUTBOUND_TASK_REASSIGN_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_REASSIGN_FAILURE,

    OutboundTypes.OUTBOUND_TASK_DEPARTURE,
    OutboundTypes.OUTBOUND_TASK_DEPARTURE_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_DEPARTURE_FAILURE,

    OutboundTypes.OUTBOUND_TASK_EDIT,
    OutboundTypes.OUTBOUND_TASK_EDIT_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_EDIT_FAILURE,

    OutboundTypes.OUTBOUND_TASK_CONVERT,
    OutboundTypes.OUTBOUND_TASK_CONVERT_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_CONVERT_FAILURE,

    OutboundTypes.OUTBOUND_GLITCH_UPDATE,
    OutboundTypes.OUTBOUND_GLITCH_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_GLITCH_UPDATE_FAILURE,

    OutboundTypes.OUTBOUND_NOTIFICATION_CREATE,
    OutboundTypes.OUTBOUND_NOTIFICATION_CREATE_SUCCESS,
    OutboundTypes.OUTBOUND_NOTIFICATION_CREATE_FAILURE,
    OutboundTypes.OUTBOUND_NOTIFICATION_PHOTO_SUCCESS,
    OutboundTypes.OUTBOUND_NOTIFICATION_PHOTO_FAILURE,

    OutboundTypes.OUTBOUND_LF_CREATE_UPLOADING_PHOTO,
    OutboundTypes.OUTBOUND_LF_CREATE_APPLY_PHOTO,
    OutboundTypes.OUTBOUND_LF_PHOTO_FAILURE,

    OutboundTypes.OUTBOUND_LF_SUBMIT,
    OutboundTypes.OUTBOUND_LF_SUBMIT_SUCCESS,
    OutboundTypes.OUTBOUND_LF_SUBMIT_FAILURE,

    OutboundTypes.OUTBOUND_ROOM_MESSAGE_ADD,
    OutboundTypes.OUTBOUND_ROOM_MESSAGE_ADD_FAILURE,

    OutboundTypes.OUTBOUND_ROOM_MESSAGE_REMOVE,
    OutboundTypes.OUTBOUND_ROOM_MESSAGE_REMOVE_FAILURE,

    OutboundTypes.OUTBOUND_ROOM_MESSAGE_UPDATE,
    OutboundTypes.OUTBOUND_ROOM_MESSAGE_UPDATE_FAILURE,

    OutboundTypes.OUTBOUND_INVENTORY_ASSET_CONSUMATION,
    OutboundTypes.OUTBOUND_INVENTORY_ASSET_CONSUMATION_SUCCESS,
    OutboundTypes.OUTBOUND_INVENTORY_ASSET_CONSUMATION_FAILURE,
    OutboundTypes.OUTBOUND_INVENTORY_CONFIRM_ASSET_CONSUMATION,
    OutboundTypes.OUTBOUND_INVENTORY_CONFIRM_ASSET_CONSUMATION_SUCCESS,
    OutboundTypes.OUTBOUND_INVENTORY_CONFIRM_ASSET_CONSUMATION_FAILURE,
    OutboundTypes.OUTBOUND_INVENTORY_WITHDRAWAL,
    OutboundTypes.OUTBOUND_INVENTORY_WITHDRAWAL_SUCCESS,
    OutboundTypes.OUTBOUND_INVENTORY_WITHDRAWAL_FAILURE,
    OutboundTypes.OUTBOUND_INVENTORY_REJECT,
    OutboundTypes.OUTBOUND_INVENTORY_REJECT_SUCCESS,
    OutboundTypes.OUTBOUND_INVENTORY_REJECT_FAILURE,

    OutboundTypes.OUTBOUND_UPDATE_FOUND_ITEM,
    OutboundTypes.OUTBOUND_UPDATE_FOUND_ITEM_SUCCESS,
    OutboundTypes.OUTBOUND_UPDATE_FOUND_ITEM_FAILURE,

    OutboundTypes.OUTBOUND_FOUND_PHOTO_EXTRA_ITEM,
    OutboundTypes.OUTBOUND_FOUND_PHOTO_EXTRA_ITEM_SUCCESS,
    OutboundTypes.OUTBOUND_FOUND_PHOTO_EXTRA_ITEM_FAILURE,

    OutboundTypes.OUTBOUND_FOUND_UPDATE_PHOTO,
    OutboundTypes.OUTBOUND_FOUND_UPDATE_PHOTO_SUCCESS,
    OutboundTypes.OUTBOUND_FOUND_UPDATE_PHOTO_FAILURE,

    OutboundTypes.OUTBOUND_UPDATE_EXTRA_OPTION,
    OutboundTypes.OUTBOUND_UPDATE_EXTRA_OPTION_SUCCESS,
    OutboundTypes.OUTBOUND_UPDATE_EXTRA_OPTION_FAILURE,

    OutboundTypes.OUTBOUND_PLANNING_BULK,
    OutboundTypes.OUTBOUND_PLANNING_BULK_SUCCESS,
    OutboundTypes.OUTBOUND_PLANNING_BULK_FAILURE,

    OutboundTypes.OUTBOUND_NIGHT_PLANNING_BULK,
    OutboundTypes.OUTBOUND_NIGHT_PLANNING_BULK_SUCCESS,
    OutboundTypes.OUTBOUND_NIGHT_PLANNING_BULK_FAILURE,

    OutboundTypes.OUTBOUND_NIGHTLY_PLANNING_STATUS_UPDATE,
    OutboundTypes.OUTBOUND_NIGHTLY_PLANNING_STATUS_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_NIGHTLY_PLANNING_STATUS_UPDATE_FAILURE,

    OutboundTypes.OUTBOUND_NIGHT_PLANNING_UPDATE,
    OutboundTypes.OUTBOUND_NIGHT_PLANNING_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_NIGHT_PLANNING_UPDATE_FAILURE,

    OutboundTypes.OUTBOUND_TASK_UPLOAD_ADD_PHOTO,
    OutboundTypes.OUTBOUND_TASK_SUBMIT_ADD_PHOTO,
    OutboundTypes.OUTBOUND_TASK_SUBMIT_ADD_PHOTO_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_SUBMIT_ADD_PHOTO_FAILURE,

    OutboundTypes.OUTBOUND_TASK_ADDITIONAL_IMAGE,
    OutboundTypes.OUTBOUND_TASK_ADDITIONAL_IMAGE_SUCCESS,
    OutboundTypes.OUTBOUND_TASK_ADDITIONAL_IMAGE_FAILURE,

    OutboundTypes.OUTBOUND_TASKS_TO_SOMEDAY,
    OutboundTypes.OUTBOUND_TASKS_TO_SOMEDAY_SUCCESS,
    OutboundTypes.OUTBOUND_TASKS_TO_SOMEDAY_FAILURE,

    OutboundTypes.OUTBOUND_TASKS_FROM_SOMEDAY,
    OutboundTypes.OUTBOUND_TASKS_FROM_SOMEDAY_SUCCESS,
    OutboundTypes.OUTBOUND_TASKS_FROM_SOMEDAY_FAILURE,

    OutboundTypes.OUTBOUND_INSPECTION_UPLOAD_PHOTO,
    OutboundTypes.OUTBOUND_INSPECTION_SUBMIT_PHOTO,
    OutboundTypes.OUTBOUND_INSPECTION_SUBMIT_PHOTO_SUCCESS,
    OutboundTypes.OUTBOUND_INSPECTION_SUBMIT_PHOTO_FAILURE,

    OutboundTypes.OUTBOUND_CREATE_AUDIT_INSERT_ROUTE,
    OutboundTypes.OUTBOUND_CREATE_AUDIT_INSERT_ROUTE_SUCESS,
    OutboundTypes.OUTBOUND_CREATE_AUDIT_INSERT_ROUTE_FAILURE,

    OutboundTypes.OUTBOUND_AUDIT_INSERT,
    OutboundTypes.OUTBOUND_AUDIT_INSERT_SUCCESS,
    OutboundTypes.OUTBOUND_AUDIT_UPDATE,
    OutboundTypes.OUTBOUND_AUDIT_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_AUDIT_REQUEST_FAILURE,

    OutboundTypes.OUTBOUND_AUDIT_DELETE,
    OutboundTypes.OUTBOUND_AUDIT_DELETE_SCCESS,
    OutboundTypes.OUTBOUND_AUDIT_DELETE_REQUEST_FAILURE,

    OutboundTypes.OUTBOUND_AUDIT_TEMPLATE_UPDATE,
    OutboundTypes.OUTBOUND_AUDIT_TEMPLATE_UPDATE_SUCCESS,
    OutboundTypes.OUTBOUND_AUDIT_TEMPLATE_REQUEST_FAILURE,

    OutboundTypes.OUTBOUND_INSPECTION_INSERT_ALL,
    OutboundTypes.OUTBOUND_INSPECTION_UPDATE_ALL,
    OutboundTypes.OUTBOUND_INSPECTION_INSERT,
    OutboundTypes.OUTBOUND_INSPECTION_UPDATE,
    OutboundTypes.OUTBOUND_INSPECTION_REQUEST_FAILURE,

    OutboundTypes.OUTBOUND_RETRY_FAILED,
    OutboundTypes.OUTBOUND_REMOVE_FAILED,

    OutboundTypes.OUTBOUND_ROOM_COMMENT_ADD,
    OutboundTypes.OUTBOUND_ROOM_COMMENT_ADD_SUCESS,
    OutboundTypes.OUTBOUND_ROOM_COMMENT_ADD_FAILURE,

    OutboundTypes.OUTBOUND_ROOM_CLEANING_ADD,
    OutboundTypes.OUTBOUND_ROOM_CLEANING_ADD_SUCESS,
    OutboundTypes.OUTBOUND_ROOM_CLEANING_ADD_FAILURE,

    OutboundTypes.OUTBOUND_ROOM_UPDATE_PRIORITY,
    OutboundTypes.OUTBOUND_ROOM_UPDATE_PRIORITY_SUCESS,
    OutboundTypes.OUTBOUND_ROOM_UPDATE_PRIORITY_FAILURE,

    OutboundTypes.OUTBOUND_LOCATOR_STATUS,
    OutboundTypes.OUTBOUND_LOCATOR_STATUS_SUCCESS,
    OutboundTypes.OUTBOUND_LOCATOR_STATUS_FAILURE,

    OutboundTypes.UPDATE_NIGHTY_INSPECTION_STATUS,
    OutboundTypes.UPDATE_NIGHTY_INSPECTION_STATUS_SUCCESS,
    OutboundTypes.UPDATE_NIGHTY_INSPECTION_STATUS_FAILED,

    OutboundTypes.OUTBOUND_ASSIGN_CLEANING,
    OutboundTypes.OUTBOUND_ASSIGN_CLEANING_SUCCESS,
    OutboundTypes.OUTBOUND_ASSIGN_CLEANING_FAILED,

    OutboundTypes.OUTBOUND_RE_ASSIGN_CLEANING,
    OutboundTypes.OUTBOUND_RE_ASSIGN_CLEANING_SUCCESS,
    OutboundTypes.OUTBOUND_RE_ASSIGN_CLEANING_FAILED,

    OutboundTypes.OUTBOUND_CENCLE_CLEANING,
    OutboundTypes.OUTBOUND_CENCLE_CLEANING_SUCCESS,
    OutboundTypes.OUTBOUND_CENCLE_CLEANING_FAILED
]